#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v18
# autospec commit: eaa4f711da30
#
Name     : MangoHud
Version  : 0.7.2
Release  : 1
URL      : https://github.com/flightlessmango/MangoHud/releases/download/v0.7.2/MangoHud-v0.7.2-Source.tar.xz
Source0  : https://github.com/flightlessmango/MangoHud/releases/download/v0.7.2/MangoHud-v0.7.2-Source.tar.xz
Summary  : Fast C++ logging library.
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause MIT Zlib
Requires: MangoHud-bin = %{version}-%{release}
Requires: MangoHud-data = %{version}-%{release}
Requires: MangoHud-lib = %{version}-%{release}
Requires: MangoHud-license = %{version}-%{release}
Requires: MangoHud-man = %{version}-%{release}
BuildRequires : appstream-bin
BuildRequires : buildreq-meson
BuildRequires : dbus-dev
BuildRequires : gcc-staticdev
BuildRequires : glslang-bin
BuildRequires : libglvnd-dev
BuildRequires : libxkbcommon-dev
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(glew)
BuildRequires : pkgconfig(glfw3)
BuildRequires : pkgconfig(nlohmann_json)
BuildRequires : pkgconfig(spdlog)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : pypi-mako
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# MangoHud
A Vulkan and OpenGL overlay for monitoring FPS, temperatures, CPU/GPU load and more.

%package bin
Summary: bin components for the MangoHud package.
Group: Binaries
Requires: MangoHud-data = %{version}-%{release}
Requires: MangoHud-license = %{version}-%{release}

%description bin
bin components for the MangoHud package.


%package data
Summary: data components for the MangoHud package.
Group: Data

%description data
data components for the MangoHud package.


%package doc
Summary: doc components for the MangoHud package.
Group: Documentation
Requires: MangoHud-man = %{version}-%{release}

%description doc
doc components for the MangoHud package.


%package lib
Summary: lib components for the MangoHud package.
Group: Libraries
Requires: MangoHud-data = %{version}-%{release}
Requires: MangoHud-license = %{version}-%{release}

%description lib
lib components for the MangoHud package.


%package license
Summary: license components for the MangoHud package.
Group: Default

%description license
license components for the MangoHud package.


%package man
Summary: man components for the MangoHud package.
Group: Default

%description man
man components for the MangoHud package.


%prep
%setup -q -n MangoHud-v0.7.2
cd %{_builddir}/MangoHud-v0.7.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1724268239
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dinclude_doc=true \
-Dmangoapp=true \
-Dmangoapp_layer=true \
-Dmangohudctl=true \
-Duse_system_spdlog=enabled \
-Dwith_wayland=enabled \
-Dwith_xnvctrl=disabled  builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/MangoHud
cp %{_builddir}/MangoHud-v%{version}/LICENSE %{buildroot}/usr/share/package-licenses/MangoHud/4eb911970608bc8d4294385a39e51525d70cbe1f || :
cp %{_builddir}/MangoHud-v%{version}/modules/minhook/LICENSE.txt %{buildroot}/usr/share/package-licenses/MangoHud/6c30d77b67f44704514f77c27fa93175b5370796 || :
cp %{_builddir}/MangoHud-v%{version}/subprojects/Vulkan-Headers-1.2.158/LICENSE.build %{buildroot}/usr/share/package-licenses/MangoHud/776236d49af728f3113a1b75a3454cfbd6681d37 || :
cp %{_builddir}/MangoHud-v%{version}/subprojects/Vulkan-Headers-1.2.158/LICENSE.txt %{buildroot}/usr/share/package-licenses/MangoHud/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/MangoHud-v%{version}/subprojects/imgui-1.89.9/LICENSE.build %{buildroot}/usr/share/package-licenses/MangoHud/622b72635c4dbb11f5b840e42f9655e3714b8026 || :
cp %{_builddir}/MangoHud-v%{version}/subprojects/imgui-1.89.9/LICENSE.txt %{buildroot}/usr/share/package-licenses/MangoHud/e8ba7aa3a16b08492de09eefb90f4dfa469f9bf5 || :
cp %{_builddir}/MangoHud-v%{version}/subprojects/imgui-1.89.9/examples/libs/glfw/COPYING.txt %{buildroot}/usr/share/package-licenses/MangoHud/04f51adf71494bbcfc359b25e34d4c16a0784e49 || :
cp %{_builddir}/MangoHud-v%{version}/subprojects/implot-0.16/LICENSE %{buildroot}/usr/share/package-licenses/MangoHud/d798fc9a411036b061e5cbe5533e3bc204aa1269 || :
cp %{_builddir}/MangoHud-v%{version}/subprojects/implot-0.16/LICENSE.build %{buildroot}/usr/share/package-licenses/MangoHud/622b72635c4dbb11f5b840e42f9655e3714b8026 || :
cp %{_builddir}/MangoHud-v%{version}/subprojects/nlohmann_json-3.10.5/LICENSE.MIT %{buildroot}/usr/share/package-licenses/MangoHud/5aa6321f397c4409e3f8f6e26481aab583dccdf8 || :
cp %{_builddir}/MangoHud-v%{version}/subprojects/spdlog-1.14.1/LICENSE %{buildroot}/usr/share/package-licenses/MangoHud/bab970f85d9d9b485a36b93f8678fff4850d76fd || :
cp %{_builddir}/MangoHud-v%{version}/subprojects/spdlog-1.14.1/LICENSE.build %{buildroot}/usr/share/package-licenses/MangoHud/622b72635c4dbb11f5b840e42f9655e3714b8026 || :
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mangoapp
/usr/bin/mangohud
/usr/bin/mangohudctl
/usr/bin/mangoplot

%files data
%defattr(-,root,root,-)
/usr/share/icons/hicolor/scalable/apps/io.github.flightlessmango.mangohud.svg
/usr/share/metainfo/io.github.flightlessmango.mangohud.metainfo.xml
/usr/share/vulkan/implicit_layer.d/MangoHud.x86_64.json
/usr/share/vulkan/implicit_layer.d/libMangoApp.x86_64.json

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/mangohud/MangoHud.conf.example
/usr/share/doc/mangohud/presets.conf.example

%files lib
%defattr(-,root,root,-)
/usr/lib64/mangohud/libMangoApp.so
/usr/lib64/mangohud/libMangoHud.so
/usr/lib64/mangohud/libMangoHud_dlsym.so
/usr/lib64/mangohud/libMangoHud_opengl.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/MangoHud/04f51adf71494bbcfc359b25e34d4c16a0784e49
/usr/share/package-licenses/MangoHud/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/MangoHud/4eb911970608bc8d4294385a39e51525d70cbe1f
/usr/share/package-licenses/MangoHud/5aa6321f397c4409e3f8f6e26481aab583dccdf8
/usr/share/package-licenses/MangoHud/622b72635c4dbb11f5b840e42f9655e3714b8026
/usr/share/package-licenses/MangoHud/6c30d77b67f44704514f77c27fa93175b5370796
/usr/share/package-licenses/MangoHud/776236d49af728f3113a1b75a3454cfbd6681d37
/usr/share/package-licenses/MangoHud/bab970f85d9d9b485a36b93f8678fff4850d76fd
/usr/share/package-licenses/MangoHud/d798fc9a411036b061e5cbe5533e3bc204aa1269
/usr/share/package-licenses/MangoHud/e8ba7aa3a16b08492de09eefb90f4dfa469f9bf5

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/mangoapp.1
/usr/share/man/man1/mangohud.1
